import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/StartMenu.module.css";
import Header from "@/components/layout/header";

import iconHTML from "../public/assets/images/icon-html.svg";
import iconCSS from "../public/assets/images/icon-css.svg";
import iconJS from "../public/assets/images/icon-js.svg";
import iconAccessibility from "../public/assets/images/icon-accessibility.svg";
import Icon from "@/components/ui/icon";

const inter = Inter({ subsets: ["latin"] });

export default function StartMenu() {
  const START_MENU_CONFIG = [
    {
      id: "html",
      text: "HTML",
      imgSrc: iconHTML,
      iconBG: "orange",
    },
    {
      id: "css",
      text: "CSS",
      imgSrc: iconCSS,
      iconBG: "green",
    },
    {
      id: "js",
      text: "Javascript",
      imgSrc: iconJS,
      iconBG: "blue",
    },
    {
      id: "accessibility",
      text: "Accessibility",
      imgSrc: iconAccessibility,
      iconBG: "purple",
    },
  ];

  const items = START_MENU_CONFIG.map(({ id, text, imgSrc, iconBG }) => {
    const iconConfig = {
      color: iconBG,
      content: { type: "icon", value: imgSrc },
      altText: `${text} image`,
    };

    return (
      <li key={id} className={styles.item}>
        <Icon {...iconConfig} />

        <h3 className="heading-S">{text}</h3>
      </li>
    );
  });

  // TODO remove iconConfig and make auto
  const iconConfig = {
    color: START_MENU_CONFIG[3].iconBG,
    content: { type: "icon", value: START_MENU_CONFIG[3].imgSrc },
    altText: `Accessibility image`,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.background}>
        <Header title="Accessibility" iconConfig={iconConfig} />
        <main className={`${styles.main} ${inter.className}`}>
          <div className={styles["content-wrapper"]}>
            <div className={styles.column}>
              <h1 className="heading-L">
                Welcome to the <br />
                <span className="heading-L--bold">Frontend Quiz!</span>
              </h1>
              <p className="body-S">Pick a subject to get started.</p>
            </div>

            <ul>{items}</ul>
          </div>
        </main>
      </div>
    </>
  );
}
