import { promises as fs } from "fs";
import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Inter } from "next/font/google";
import styles from "@/styles/StartMenu.module.css";
import Header from "@/components/layout/header";
import Icon from "@/components/ui/icon";
import ItemRow from "@/components/ui/itemRow";

const inter = Inter({ subsets: ["latin"] });

function StartMenu({ startMenuConfig }) {
  const router = useRouter();

  const items = startMenuConfig.map(({ id, text, imgSrc, iconBG }) => {
    const iconConfig = {
      color: iconBG,
      content: { type: "icon", value: imgSrc },
      altText: `${text} image`,
    };

    const onQuizSelected = (id) => {
      console.log(id);
      router.push({
        pathname: "questions/[quiz]/[id]",
        query: { id: 1, quiz: id },
      });
    };

    return (
      <ItemRow
        key={id}
        id={id}
        content={text}
        onRowClick={() => onQuizSelected(id)}
        iconConfig={iconConfig}
      />
    );
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.background}>
        <Header />
        <main className={`${styles.main} ${inter.className}`}>
          <div className={styles["content-wrapper"]}>
            <div className={styles.column}>
              <h1 className="heading-L">
                Welcome to the <br />
                <span className="heading-L--bold">Frontend Quiz!</span>
              </h1>
              <p className="body-S">Pick a subject to get started.</p>
            </div>

            <ul>{items}</ul>
          </div>
        </main>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const jsonData = await fs.readFile(process.cwd() + "/data/data.json", "utf8");
  const data = JSON.parse(jsonData);
  let startMenuConfig = [];

  if (data && data.quizzes) {
    const colorBG = {
      HTML: "orange",
      CSS: "green",
      JavaScript: "blue",
      Accessibility: "purple",
    };

    startMenuConfig = data.quizzes.map(({ title, icon }) => {
      return {
        id: title,
        text: title,
        imgSrc: icon,
        iconBG: colorBG[title] || "orange",
      };
    });
  } else {
    return {
      notFound: true,
    };
  }

  return { props: { startMenuConfig } };
}

export default StartMenu;
